apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static   # PV name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # we should give 30Gi or less then 30Gi, because i have volumenonly 30Gi