apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static   # PV name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # we should give 30Gi or less then 30Gi, because i have volumenonly 30Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html     # This directory i want to place into disk from POD
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static  # here claimName and  volumeName  both should be same name