apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "ebs-sc"     # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 19Gi  # we should give 30Gi or less then 30Gi, because i have volumenonly 30Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    purpose: "ebs-dynamic-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html     # This directory i want to place into disk from POD
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic    # here claimName and  name in metadata for PersistentVolumeClaim  both should be same name

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-dynamic
spec:
  type: LoadBalancer
  selector:     #labels are used as selectors
    purpose: "ebs-dynamic-demo"
  ports:
  - protocol: TCP
    port: 80    #service port
    targetPort: 80   #target container port
    nodePort: 30007
