apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-expense"
  resources:
    requests:
      storage: 5Gi     # this is dummy, as we know that EFS can be scaled automatically, we can give any value in this section.

---

apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    purpose: "efs-dynamic-demo"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html     # This directory i want to place into disk from POD
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-dynamic  # here claimName and  name in metadata for PersistentVolumeClaim  both should be same name

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:     #labels are used as selectors
    purpose: "efs-dynamic-demo"
  ports:
  - protocol: TCP
    port: 80    #service port
    targetPort: 80   #target container port
    nodePort: 30007
