apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
type: Opaque
data:
# we should not give direct test, we need to give base64 format
  username: YWRtaW4=
  password: YWRtaW4xMjM=






#echo -n "admin" | base64
#YWRtaW4=

#echo "YWRtaW4=" | base64 --decode
#admin


apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-pod
spec:
  containers:
  - name: nginx-demo-container
    image: nginx
    env:
    - name: UserName
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: PassWord
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
