apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  # these labels are replicaset labels
  labels:
    app: frontend
    tier: web
spec:
  # modify replicas according to your case
  replicas: 7
  selector:
  # As we have many pods ,we should give what labels the replicaset to match
    matchLabels:
      app: frontend
      tier: web
  # pod template
  template:
    metadata:
      name: nginx-pod
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl