apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels of deployemnt resource
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
  # As we have many pods ,we should give what labels the deployment to match
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  # pod template
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: jayakrishna1993/deployment:1.3.0
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:     #labels are used as selectors
    app: nginx
    tier: frontend
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80    #service port
    targetPort: 80   #target container port
    nodePort: 30007
